application: swarmdraw
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: client.html
  upload: client.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /table_generation\.js
  static_files: table_generation.js
  upload: table_generation.js

- url: /client.js
  static_files: client.js
  upload: client.js

- url: /style_client\.css
  static_files: style_client.css
  upload: style_client.css

- url: /bug_labs_logo\.png
  static_files: bug_labs_logo.png
  upload: bug_labs_logo.png
